libraryapp/urls.py
from django.urls import include, path
from .views import *

app_name = "libraryapp"

urlpatterns = [
    path('', home, name='home'),
    path('books/', book_list, name='books'),
    path('book/form', book_form, name='book_form'),
    path('books/<int:book_id>/', book_details, name='book'),

    path('libraries/', list_libraries, name='libraries'),
    path('library/form', library_form, name='library_form'),
    path('libraries/<int:library_id>/', library_details, name='library'),

    path('librarians/', list_librarians, name='librarians'),
    path('librarians/<int:librarian_id>/', librarian_details, name='librarians'),
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_user, name='logout'),
]

libraryproject/urls.py
from django.contrib import admin
from django.urls import include, path
from libraryapp.models import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libraryapp.urls')),
]

libraryapp/models.py
from django.db import models

# Create your models here.

libraryapp/models/book.py
from django.db import models
from .library import Library
from .librarian import Librarian

class Book(models.Model):
    """Model definition for Book."""

    title = models.CharField(max_length=50)
    isbn = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    year_published = models.IntegerField()
    location = models.ForeignKey(Library, on_delete=models.CASCADE)
    librarian = models.ForeignKey(Librarian, on_delete=models.CASCADE)
    
    # TODO: Define fields here

    class Meta:
        """Meta definition for Book."""

        verbose_name = ('Book')
        verbose_name_plural = ('Books')

    def __str__(self):
        """Unicode representation of Book."""
        pass
    

libraryapp/models/librarian.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .library import Library


class Librarian(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.ForeignKey(
        Library, related_name="librarians",
        null=True, # Makes column nullable in DB
        blank=True, # Allows blank value on objects
        on_delete=models.CASCADE)


# These receiver hooks allow you to continue to
# work with the `User` class in your Python code.


# Every time a `User` is created, a matching `Librarian`
# object will be created and attached as a one-to-one
# property
@receiver(post_save, sender=User)
def create_librarian(sender, instance, created, **kwargs):
    if created:
        Librarian.objects.create(user=instance)

# Every time a `User` is saved, its matching `Librarian`
# object will be saved.
@receiver(post_save, sender=User)
def save_librarian(sender, instance, **kwargs):
    instance.librarian.save()

libraryapp/models/library.py
from django.db import models

class Library(models.Model):
    """Model definition for Library."""

    title = models.CharField(max_length=50)
    address = models.CharField(max_length=100)

    class Meta:
        """Meta definition for Library."""

        verbose_name = 'Library'
        verbose_name_plural = 'Librarys'

    def __str__(self):
        """Unicode representation of Library."""
        pass

libraryapp/models/modelfactory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

libraryapp/views.py
from django.shortcuts import render

# Create your views here.

libraryapp/views/connection.py
class Connection:
    db_path = "/Users/newuser/python_workspace/book_3/library-management/libraryproject/db.sqlite3"

libraryapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

libraryapp/templates/books/detail.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>{{ book.title }}</h1>
    <h2>By {{ book.author }}</h2>

    <div>Published in {{ book.year_published }}</div>
    <div>ISBN: {{ book.isbn }}</div>
  </body>
</html>

libraryapp/templates/books/form.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Inventory Book</h1>


    <form action="{% url 'libraryapp:books' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="title">Title: </label>
          <input id="title" type="text" name="title">
      </fieldset>
      <fieldset>
          <label for="author">Author: </label>
          <input id="author" type="text" name="author">
      </fieldset>
      <fieldset>
          <label for="year_published">Year of publication: </label>
          <input id="year_published" type="number" name="year_published">
      </fieldset>
      <fieldset>
          <label for="isbn">ISBN: </label>
          <input id="isbn" type="text" name="isbn">
      </fieldset>
      <fieldset>
          <label for="location">Library: </label>
          <select id="location" type="text" name="location">
                {% for library in all_libraries %}
                    <option value="{{ library.id }}">{{ library.title }}</option>
                {% endfor %}
          </select>
      </fieldset>

      <input type="submit" value="Add It" />
    </form>
  </body>
</html>

libraryapp/templates/books/librarians/list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Librarians</h1>

    <ol>
    {% for librarian in all_librarians %}
        <li>{{ librarian.first_name }} {{ librarian.last_name }}</li>
    {% endfor %}
    </ol>
  </body>
</html>

libraryapp/templates/books/list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Books</h1>

    <ol>
    {% for book in all_books %}
        <li>
            <a href="{% url 'libraryapp:book' book.id %}"> {{ book.title }} </a>
            by {{book.author}} published in {{book.year_published}}
        </li>
    {% endfor %}
    </ol>
  </body>
</html>

libraryapp/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Nashville Library Management System</title>
</head>

<body>

    <h1>Welcome to the Nashville Library Management System</h1>

</body>

</html>

libraryapp/templates/librarians/details.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>{{ librarian.first_name}} {{ librarian.last_name  }}</h1>
    <h2>Joined in {{ librarian.date_joined }}</h2>
  </body>
</html>

libraryapp/templates/librarians/form.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Inventory Book</h1>


    <form action="{% url 'libraryapp:librarians %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="title">Title: </label>
          <input id="title" type="text" name="title">
      </fieldset>
      <fieldset>
          <label for="author">Author: </label>
          <input id="author" type="text" name="author">
      </fieldset>
      <fieldset>
          <label for="year_published">Year of publication: </label>
          <input id="year_published" type="number" name="year_published">
      </fieldset>
      <fieldset>
          <label for="isbn">ISBN: </label>
          <input id="isbn" type="text" name="isbn">
      </fieldset>
      <fieldset>
          <label for="location">Library: </label>
          <select id="location" type="text" name="location">
                {% for library in all_libraries %}
                    <option value="{{ library.id }}">{{ library.title }}</option>
                {% endfor %}
          </select>
      </fieldset>

      <input type="submit" value="Add It" />
    </form>
  </body>
</html>

libraryapp/templates/librarians/list.html
{%load static%}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Librarians</h1>

    <ol>
    {% for librarian in all_librarians %}
    <li>
        <a href="{% url 'libraryapp:librarians' librarian.id %}"> {{ librarian.first_name }} {{ librarian.last_name  }} </a>
        first joined in {{ librarian.date_joined }}
    </li>
    {% endfor %}
    </ol>
  </body>
</html>

libraryapp/templates/libraries/details.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>{{ library.title }}</h1>
    <h2>By {{ library.address }}</h2>
  </body>
</html>

libraryapp/templates/libraries/form.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Add a Library</h1>

    <form action="{% url 'libraryapp:libraries' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="title">Title: </label>
          <input id="title" type="text" name="title">
      </fieldset>

      <fieldset>
          <label for="address">Address: </label>
          <input id="address" type="text" name="address">
      </fieldset>

      <input type="submit" value="Add It" />
    </form>
  </body>
</html>

libraryapp/templates/libraries/list.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Libraries</h1>

    <ol>
    {% for library in all_libraries %}
        <li>
            <a href="{% url 'libraryapp:library' library.id %}"> {{ library.title }} </a>
            is located at {{ library.address }}
        </li>
    {% endfor %}
    </ol>
  </body>
</html>